# Generated by Django 4.2 on 2024-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildmahome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
